### ISSUE TITLE
If you login in with a user account other than the jupyterhub installation account, user spwaning does not work

### ISSUE THREAD

**Issue by gigascake** [CNES/autologout-labextension#2]
There are huge bugs in this open source. Problem: If you login in with a user account other than the jupyterhub installation account, user spwaning does not work, and a '404 not found' page is displayed.
Because of this module, I'm in tears once again while switching from jupyterhub to jupyterlab. Should I master labextension development? Please confirm.

jupyterlab : 3.4.7>=3.3.2

**Comment by gigascake** [comment]
It's my fault. You forgot to specify the user group. So the problem was solved.

**Comment by guillaumeeb** [comment]
Hi @gigascake,

I'm glad you found the solution to your problem.

However, I just wanted to stress some important problems in your first comment of this issue:
- "There are huge bugs in this open source": I think this is not appropriate to open an issue with this kind of introduction. This doesn't make maintainers in a good position for helping you. Please moderate your words, even if you're upset. At the end of the comment, I can see a "Please", but it sounds more like an order to me.
- Your problem is really unclear, it's impossible to understand the link with your problem and this repository. Please try to better explain the bug you encounter the next time you open an issue.

I hope this module is still useful for you, and you'll keep in mind my answer here for any issue you might raise here or in other open source projects.

**Comment by gigascake** [comment]
sorry. I'm not used to English, so it was rude. Thanks for making a great module.

**Comment by guillaumeeb** [comment]
Yes, I was wondering also if this might be a barrier language, I'm also glad you make that clearer, and no offense taken in the end.
